apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- worker_staging_deployment.yaml
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "8378185 Inc"
