---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: redis-staging
  namespace: instavote
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: redis-staging
  providerRef:
    name: github-instavote

