---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  gitImplementation: go-git
  interval: 1h
  ref:
    branch: main
  secretRef:
    name: github-instavote      
  timeout: 20s
  url: https://github.com/rotimi-98/instavote-deploy.git

