---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis-staging
  namespace: flux-system
spec:
  interval: 1h
  path: ./kustomize/redis/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: redis
      namespace: instavote
  timeout: 1m    

