---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: worker-staging
  namespace: instavote
spec:
        #  dependsOn:
        #  - name: redis-dev
  interval: 1h
  path: ./kustomize/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: worker
      namespace: instavote
  timeout: 1m    

